njsa:
  njsa:
    image:
      repository: artifacts.developer.gov.bc.ca/nc74-gen-docker-local
      tag: latest
    imagePullPolicy: IfNotPresent
    # imagePullSecrets specifies docker-registry secret names as an array
    imagePullSecrets:
      - name: artifactory-pull
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
  host: ""
njsaConfig:
  NODE_ENV: "production"
  REACT_APP_APP_DOMAIN: ""
  REACT_APP_API_DOMAIN: ""
  REACT_APP_APP_PATH: "/"
  REACT_APP_AUTH_SCOPE: "profile"
  REACT_APP_AUTH_URL: ""
  REACT_APP_AUTH_REALM: "standard"
  REACT_APP_AUTH_ROLE: "newjobsurveyadmin"
  REACT_APP_AUTH_CLIENT_ID: "new-job-survey-admin-4360"
