njsa:
  njsa:
    image:
      repository: artifacts.developer.gov.bc.ca/nc74-gen-docker-local
    imagePullPolicy: IfNotPresent
    # imagePullSecrets specifies docker-registry secret names as an array
    imagePullSecrets:
      - name: artifactory-pull
    tag: latest
    resources:
      limits:
        cpu: 150m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  replicas: 1
  revisionHistoryLimit: 10
  type: ClusterIP
  host: ""
njsaConfig:
  ENVJs: ""
