njsa:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
njsaConfig:
  ENVJs: |-
    window.__ENV = {
      NODE_ENV: 'production',
      REACT_APP_APP_DOMAIN: 'https://erap.apps.gov.bc.ca/newjobsurveyadmin/',
      REACT_APP_API_DOMAIN: 'https://erap.apps.gov.bc.ca/newjobsurveyadmin-api',
      REACT_APP_APP_PATH: '/',
      REACT_APP_AUTH_SCOPE: 'profile',
      REACT_APP_AUTH_URL: 'https://loginproxy.gov.bc.ca/auth',
      REACT_APP_AUTH_REALM: 'standard',
      REACT_APP_AUTH_ROLE: 'newjobsurveyadmin',
      REACT_APP_AUTH_CLIENT_ID: 'new-job-survey-admin-4360',
    }