backupConf:
  backupConf: |-
    postgres=postgresql:5432/njsa
    30 1 * * * default ./backup.sh -s
    30 2 * * * default ./backup.sh -s -v all
njsa:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
njsaApi:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
njsaApiConfig:
  appsettingsJson: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Debug",
          "System": "Information",
          "Microsoft": "Information"
        }
      },
      "CallWebApi": {
        "BaseUrl": "https://erap.apps.gov.bc.ca/newjobsurveyadmin-callwebapi/api/NjsaCallWeb/"
      },
      "Sieve": {
        "ThrowExceptions": true
      }
    }
njsaConfig:
  ENVJs: |-
    window.__ENV = {
      NODE_ENV: 'production',
      REACT_APP_APP_DOMAIN: 'https://erap.apps.gov.bc.ca/newjobsurveyadmin/',
      REACT_APP_API_DOMAIN: 'https://erap.apps.gov.bc.ca/newjobsurveyadmin-api',
      REACT_APP_APP_PATH: '/',
      REACT_APP_AUTH_SCOPE: 'profile',
      REACT_APP_AUTH_URL: 'https://loginproxy.gov.bc.ca/auth',
      REACT_APP_AUTH_REALM: 'standard',
      REACT_APP_AUTH_ROLE: 'newjobsurveyadmin',
      REACT_APP_AUTH_CLIENT_ID: 'new-job-survey-admin-4360',
    }
postgresql:
  databaseAdminPassword: ""
  databaseName: ""
  databasePassword: ""
  databaseUser: ""
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  type: ClusterIP
pvc:
  backupPostgresqlPvc:
    storageClass: netapp-file-backup
    storageRequest: 20Gi
  backupVerification:
    storageClass: netapp-file-standard
    storageRequest: 5Gi
  postgresql:
    storageClass: netapp-file-standard
    storageRequest: 2Gi
scheduledPull:
  cronjobProd:
    args:
    - /bin/sh
    - -c
    - date; echo "Starting scheduled task cron"; curl -i -d "" -X POST https://erap.apps.gov.bc.ca/newjobsurveyadmin-api/api/Employees/ScheduledLoadAndUpdate;
    image:
      repository: artifacts.developer.gov.bc.ca/docker-remote/curlimages/curl
      tag: 7.79.1
    imagePullPolicy: IfNotPresent
  failedJobsHistoryLimit: 1
  schedule: 0 16 * * *
  successfulJobsHistoryLimit: 3
  suspend: false