apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chart.fullname" . }}-allow-traffic-from-gateway-to-njsa
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          environment: test
          name: 264e6f
  - from:
    - namespaceSelector:
        matchLabels:
          environment: prod
          name: 264e6f
  - from:
    - namespaceSelector:
        matchLabels:
          environment: test
          name: b8840c
  - from:
    - namespaceSelector:
        matchLabels:
          environment: prod
          name: b8840c
  podSelector:
    matchExpressions:
    - key: deployment
      operator: In
      values:
      - njsa
      - njsa-api
      - callwebapi
  policyTypes:
  - Ingress