apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-njsa-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  __ENV.js: {{ .Values.njsaConfig.ENVJs | toYaml | indent 1 }}