apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart.fullname" . }}-njsa
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: njsa
    weight: 100
  wildcardPolicy: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-njsa
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.njsa.type }}
  selector:
    deployment: njsa
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.njsa.ports | toYaml | nindent 2 }}