apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-verification
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.backupVerification.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.backupVerification.storageClass | quote }}
  volumeMode: Filesystem