apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-backup-postgresql-pvc
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.backupPostgresqlPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.backupPostgresqlPvc.storageClass | quote }}
  volumeMode: Filesystem
  volumeName: pvc-43c8eb0f-4338-4384-92ef-0e483b7fad63