apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.fullname" . }}-backup-verification
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.backupVerification.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.backupVerification.storageClass | quote }}
  volumeMode: Filesystem
  volumeName: pvc-8a66f5f9-1666-4cb9-98d7-32300826366f