apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-backup-conf
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  backup.conf: {{ .Values.backupConf.backupConf | toYaml | indent 1 }}