apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-postgresql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.backupPostgresqlPvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.backupPostgresqlPvc.storageClass | quote }}
  volumeMode: Filesystem