apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-njsa-api-secret
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  appsettings.json: {{ required "njsaApiSecret.appsettingsJson is required" .Values.njsaApiSecret.appsettingsJson
    | b64enc | quote }}
type: Opaque