kind: Secret
apiVersion: v1
metadata:
  name: njsa-api-secret
  labels:
  {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData: 
  appsettings.json: |
    {
      "ConnectionStrings": {
        "NewJobSurveyAdmin": "{{ .Values.njsaApiSecret.ConnectionStrings.NewJobSurveyAdmin }}"
      },
      "Authentication": {
        "Authority": "{{ .Values.njsaApiSecret.Authentication.Authority }}",
        "RoleName": "{{ .Values.njsaApiSecret.Authentication.RoleName }}",
        "RoleClaimType": "{{ .Values.njsaApiSecret.Authentication.RoleClaimType }}",
        "Audience": "{{ .Values.njsaApiSecret.Authentication.Audience }}"
      },
      "Email": {
        "FromName": "{{ .Values.njsaApiSecret.Email.FromName }}",
        "FromAddress": "{{ .Values.njsaApiSecret.Email.FromAddress }}",
        "ToName": "{{ .Values.njsaApiSecret.Email.ToName }}",
        "ToAddress": "{{ .Values.njsaApiSecret.Email.ToAddress }}",
        "SmtpServer": "{{ .Values.njsaApiSecret.Email.SmtpServer }}",
        "SmtpPort": {{ .Values.njsaApiSecret.Email.SmtpPort }}
      },
      "LdapLookup": {
        "Host": "{{ .Values.njsaApiSecret.LdapLookup.Host }}",
        "TrustedIssuers": "{{ .Values.njsaApiSecret.LdapLookup.TrustedIssuers }}",
        "Port": {{ .Values.njsaApiSecret.LdapLookup.Port }},
        "Base": "{{ .Values.njsaApiSecret.LdapLookup.Base }}",
        "Username": "{{ .Values.njsaApiSecret.LdapLookup.Username }}",
        "Password": "{{ .Values.njsaApiSecret.LdapLookup.Password }}",
        "OverrideEmail": "{{ .Values.njsaApiSecret.LdapLookup.OverrideEmail }}"
      },
      "CallWebApi": {
        "TokenRequestUrl": "{{ .Values.njsaApiSecret.CallWebApi.TokenRequestUrl }}",
        "ClientId": "{{ .Values.njsaApiSecret.CallWebApi.ClientId }}",
        "ClientSecret": "{{ .Values.njsaApiSecret.CallWebApi.ClientSecret }}"
      },
      "PsaApi": {
        "NjsaDataUrl": "{{ .Values.njsaApiSecret.PsaApi.NjsaDataUrl }}",
        "ClientUsername": "{{ .Values.njsaApiSecret.PsaApi.ClientUsername }}",
        "ClientPassword": "{{ .Values.njsaApiSecret.PsaApi.ClientPassword }}"
      }
    }