apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled-pull
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: {{ .Values.scheduledPull.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args: {{- toYaml .Values.scheduledPull.cronjobProd.args | nindent 8 }}
            image: {{ .Values.scheduledPull.cronjobProd.image.repository }}:{{ .Values.scheduledPull.cronjobProd.image.tag
              | default .Chart.AppVersion }}
            imagePullPolicy: {{ .Values.scheduledPull.cronjobProd.imagePullPolicy
              }}
            name: cronjob-prod
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: cronjob-artifactory-secret
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: {{ .Values.scheduledPull.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.scheduledPull.successfulJobsHistoryLimit
    }}
  suspend: {{ .Values.scheduledPull.suspend }}