njsaApi:
  njsaApi:
    resources:
      limits:
        cpu: 150m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
postgresql:
  postgresql:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 512Mi
        cpu: 250m
pvc:
  backupPostgresqlPvc:
    storageClass: netapp-file-backup
    storageRequest: 2Gi
  backupVerification:
    storageClass: netapp-file-standard
    storageRequest: 2Gi
  postgresql:
    storageClass: netapp-file-standard
    storageRequest: 10Gi
